watches/main/urls.py
from django.urls import path

from .views import (buyback_view_page, index_page_view, search_view,
                    watches_details_page_view, watches_page_view,
                    watches_valuation_page_view)

app_name = 'main'

urlpatterns = [
    path('', index_page_view, name='index'),
    path('search', search_view, name='search'),
    path('buyback', buyback_view_page, name='buyback'),
    path('watches', watches_page_view, name='watches'),
    path(
        'watches-details/<int:watch_id>/',
        watches_details_page_view,
        name='watches_details'
    ),
    path('watches-valuation', watches_valuation_page_view, name='valuation'),
]

watches/utility_pages/urls.py
from django.urls import path

from .views import (about_page_view, confidential_page_view,
                    contacts_page_view, faq_page_view, terms_page_view)

app_name = 'utility_pages'

urlpatterns = [
    path('about', about_page_view, name='about'),
    path('contacts', contacts_page_view, name='contacts'),
    path('faq', faq_page_view, name='faq'),
    path('confidential', confidential_page_view, name='confidential'),
    path('terms', terms_page_view, name='terms'),
]

watches/watches/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'utility_pages.views.page_not_found'
handler500 = 'utility_pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('forms.urls')),
    path('', include('utility_pages.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

watches/templates/includes/extend_form.html
<form action="#" class="form-style2">
    <div class="form-inner">
        <h3 class="form-title h3"><strong class="text-theme">Оставить заявку</strong></h3>
        <h3 class="form-title h6">Ваши контактные данные</h3>
        <div class="row">
            {% comment %} <span class="text-theme">50,000 students</span> {% endcomment %}
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="name" id="name" placeholder="Имя">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="email" id="email" placeholder="Почта">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <select name="coursenames" id="coursenames">
                        <option selected disabled hidden>Способ связи</option>
                        <option>Звонок</option>
                        <option>Telegram</option>
                        <option>WhatsUp</option>
                        <option>Viber</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="email" id="phone" placeholder="Телефон">
                </div>
            </div>
        </div>
        <h3 class="form-title h6">Информация о часах</h3>
        <div class="row">
            {% comment %} <span class="text-theme">50,000 students</span> {% endcomment %}
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="name" id="name" placeholder="Бренд">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="email" id="email" placeholder="Модель">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="email" id="phone" placeholder="Год">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input type="text" name="email" id="phone" placeholder="Цена">
                </div>
            </div>
        </div>
        <h3 class="form-title h6">Состояние и комплектация</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <select name="coursenames" id="coursenames">
                        <option selected disabled hidden>Состояние</option>
                        <option>Идеальное</option>
                        <option>Новое</option>
                        <option>Естественные следы носки</option>
                        <option>Есть дефекты</option>
                        <option>Требуется ремонт</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <select name="coursenames" id="coursenames">
                        <option selected disabled hidden>Комплектация</option>
                        <option>С упаковкой</option>
                        <option>Без упаковки</option>
                    </select>
                </div>
            </div>
        </div>
        <h3 class="form-title h6">Выберите фото часов</h3>
        <div class="row">
            <div class="col-md-6 col-xl-12">
                <div class="form-group">
                    <input class="form-control" type="file" id="formFileMultiple" multiple>
                    <label for="formFileMultiple" class="form-label">Возможные форматы: png, jpg, jpeg</label>
                </div>
            </div>
        </div>
        <div class="col-12 text-center">
            <button type="button" class="vs-btn">Отправить</button>
        </div>
        <div class="col-12 text-center">
            <div class="custom-checkbox notice">
                <label for="wp-comment-cookies-consent"> Нажимая кнопку «Отправить», Вы соглашаетесь с <a href="{% url 'main:confidential' %}">политикой конфиденциальности</a> и <a href="{% url 'main:terms' %}">пользовательским соглашением</a>.</label>
            </div>
            <a class="form-link" href="{% url 'main:faq' %}">Часто задаваемые вопросы</a>
        </div>
    </div>
    <div class="vs-circle color2"></div>
</form>

watches/templates/includes/footer.html
<footer class="footer-wrapper footer-layout3">
    <div class="shape-mockup jump d-none d-xl-block" data-left="-270px" data-bottom="-60px">
        <div class="vs-border-circle"></div>
    </div>
    <div class="widget-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-4 text-center text-lg-start">
                    <div class="widget footer-widget">
                        <div class="footer-logo mx-auto mx-lg-0"> <a href="{% url 'main:index' %}"><img src="/assets/img/logo.svg" alt="logo"></a> </div>
                        <p class="footer-text">Мы предлагаем эксклюзивные швейцарские часы от ведущих мировых брендов.</p>
                        <p class="footer-text">Высокое качество и аутентичность гарантированы.</p>
                    </div>
                    <div class="widget footer-widget">
                        <p class="footer-info"><i class="fal fa-phone-alt"></i><a class="text-inherit" href="tel:+79608889293" target="_blank">+7 (960) 888-92-93</a></p>
                        <p class="footer-info"><i class="fal fa-envelope"></i><a class="text-inherit" href="mailto:yellow.watch24@gmail.com" target="_blank">yellow.watch24@gmail.com</a></p>
                    </div>
                </div>
                <div class="col-md-6 col-lg-2">
                    <div class="widget nav_menu footer-widget">
                        <h3 class="widget_title">Разделы сайта</h3>
                        <div class="menu-all-pages-container footer-menu">
                            <ul class="menu">
                                <li><a href="{% url 'main:buyback' %}">Выкуп часов</a></li>
                                <li><a href="{% url 'main:watches' %}">Продажа часов</a></li>
                                <li><a href="{% url 'main:valuation' %}">Оценка</a></li>
                                <li><a href="{% url 'utility_pages:faq' %}">Вопросы</a></li>
                                <li><a href="{% url 'utility_pages:contacts' %}">Контакты</a></li>
                                <li><a href="{% url 'utility_pages:about' %}">О нас</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="widget footer-widget">
                        <h4 class="widget_title">Остались вопросы? Напиши нам!</h4>
                        {% include "forms/footer_form.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-wrap">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="text-center col-lg-auto">
                    <p class="copyright-text">©2024, Часовой бутик «YellowWatch»</p>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <div class="social-style1">
                        <a href="https://t.me/ant_toys" title="telegram" target="_blank"><i class="fab fa-telegram-plane"></i>Telegram</a>
                        <a href="https://wa.me/+79608889293" title="whatsapp" target="_blank"><i class="fab fa-whatsapp"></i>Whatsapp</a>
                        <a href="https://www.instagram.com/rostovtsev_ant/" title="instagram" target="_blank"><i class="fab fa-instagram"></i>Instagram</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Scroll To Top -->
<a class="scrollToTop scroll-btn"><i class="far fa-arrow-up"></i></a>

watches/templates/includes/header.html
<!--==============================
  Mobile Menu
============================== -->
<div class="vs-menu-wrapper">
    <div class="vs-menu-area text-center">
        <button class="vs-menu-toggle"><i class="fal fa-times"></i></button>
        <div class="mobile-logo">
            <a href="{% url 'main:index' %}"><img src="/assets/img/logo.svg" alt="Educino"></a>
        </div>
        <div class="vs-mobile-menu">
            <ul>
                <li>
                    <a href="{% url 'main:buyback' %}">Выкуп часов</a>
                </li>
                <li>
                    <a href="{% url 'main:watches' %}">Продажа часов</a>
                </li>
                <li>
                    <a href="{% url 'main:valuation' %}">Оценка</a>
                </li>
                <li>
                    <a href="{% url 'utility_pages:contacts' %}">Контакты</a>
                </li>
                <li>
                    <a href="{% url 'utility_pages:faq' %}">Вопросы</a>
                </li>
                <li>
                    <a href="{% url 'utility_pages:about' %}">О нас</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!--==============================
  Popup Search Box
============================== -->
<div class="popup-search-box d-none d-lg-block  ">
    <button class="searchClose"><i class="fal fa-times"></i></button>
    <form action="{% url 'main:search' %}" method="GET">
        <input type="text" class="border-theme" name="search" placeholder="Что Вас интересует?">
        <button type="submit"><i class="fal fa-search"></i></button>
    </form>
</div>
<!--==============================
  Header Area
==============================-->
{% with request.resolver_match.view_name as view_name %}
<div class="header-top">
    <div class="container">
        <div class="row justify-content-between align-items-center gx-50">
            <div class="col d-none d-xl-block">
                <div class="header-links">
                    <ul>
                        <li><i class="fas fa-phone-alt"></i>Телефон: <a href="tel:+79608889293" target="_blank">+7 (960) 888-92-93</a></li>
                        <li><i class="fas fa-envelope"></i>Почта: <a href="mailto:yellow.watch24@gmail.com" target="_blank">yellow.watch24@gmail.com</a></li>
                    </ul>
                </div>
            </div>
            <div class="col col-xl-auto d-none d-md-block">
            </div>
            <div class="col-md-auto text-center">
                <div class="header-social">
                    <a href="https://t.me/ant_toys" title="telegram" target="_blank"><i class="fab fa-telegram-plane"></i></a>
                    <a href="https://wa.me/+79608889293" title="whatsapp" target="_blank"><i class="fab fa-whatsapp"></i></a>
                    <a href="https://www.instagram.com/rostovtsev_ant/" title="instagram" target="_blank"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
    {% if view_name == 'main:index' %}
        <header class="vs-header header-layout3">
    {% else %}
        <header class="vs-header header-layout1">
    {% endif %}
    <div class="sticky-wrapper">
        <div class="sticky-active">
            <div class="container position-relative z-index-common">
                <div class="row align-items-center justify-content-between gx-50">
                    <div class="col">
                        <div class="vs-logo">
                            <a href="{% url 'main:index' %}"><img src="/assets/img/logo.svg" alt="logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <nav class="main-menu menu-style1 d-none d-lg-block">
                            <ul>
                                <li> <a href="{% url 'main:buyback' %}">Выкуп часов</a></li>
                                <li> <a href="{% url 'main:watches' %}">Продажа часов</a></li>
                                <li> <a href="{% url 'main:valuation' %}">Оценка</a></li>
                                <li> <a href="{% url 'utility_pages:contacts' %}">Контакты</a></li>
                                <li><a href="{% url 'utility_pages:faq' %}">Вопросы</a></li>
                                <li> <a href="{% url 'utility_pages:about' %}">О нас</a></li>
                            </ul>
                        </nav>
                        <button class="vs-menu-toggle d-inline-block d-lg-none"><i class="fal fa-bars"></i></button>
                    </div>
                    <div class="col-auto d-none d-xl-block">
                        <div class="header-btns">
                            <button type="button" class="searchBoxTggler"><i class="far fa-search"></i></button>
                            <button type="button" class="vs-btn style6" data-bs-toggle="modal" data-bs-target="#exampleModal1">Заказать звонок</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "modals/modal.html" %}
{% endwith %}
</header>

watches/templates/includes/pagination.html
{% load watches_extra %}

{% if page_obj.has_other_pages %}
    <div class="vs-pagination">
        <ul>
            {% if page_obj.has_previous %}
            <li class="prev">
                <a href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Предыдущая</a>
            </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if i == page_obj.number %}
                    <li class="active"><span>{{ i }}</span></li>
                {% elif i > page_obj.number|add:"-3" and i < page_obj.number|add:"3" %}
                    <li><a href="{% relative_url i 'page' request.GET.urlencode %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="next">
                <a href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">Следующая</a>
            </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

watches/templates/includes/watches_card.html
<div class="col-md-6 col-xl-12">
    <div class="course-style4">
        <div class="course-img">
            <a href="course-details.html"><img class="w-100" src="assets/img/course/course-3-1.jpg" alt="Course Img"></a>
        </div>
        <div class="course-content">
            <div class="course-category"><a href="course.html">Busniess Learning</a></div>
            <h3 class="course-name"><a href="course-details.html">Advance Begineer's Goal & Managing Quality Course</a></h3>
            <div class="course-meta">
                <a href="course.html"><i class="fas fa-user-tie"></i><span class="total-student">204 Students</span></a>
                <a href="course.html"><i class="far fa-tv"></i><span class="course-hour">12 Leson</span></a>
                <a href="course.html"><i class="fal fa-clock"></i><span class="course-hour">2h 11m</span></a>
            </div>
            <div class="course-price">
                <span class="price"><del>$259</del> $149</span>
                <small class="discount">50% Off</small>
            </div>
            <div class="course-bottom">
                <div class="course-author">
                    <a href="team-details.html" class="text-inherit"><img src="assets/img/about/author-3-1.png" alt="About Author">By Ana Watson</a>
                </div>
            </div>
            <a href="https://www.youtube.com/watch?v=_sI_Ps7JSEk" class="vs-btn style5 popup-video"><i class="fas fa-play"></i>Preview Course</a>
        </div>
    </div>
</div>

watches/templates/includes/watches_indexpage_card.html
<div class="col-md-6 col-xl-12">
    <div class="course-style4">
        <div class="image-container">
            {% if watch.image %}
                <a href="{% url 'main:watches_details' watch.id %}"><img class="w-100" src="{{ watch.image.url }}" alt="Course Img"></a>
            {% else %}
                <a href="{% url 'main:watches_details' watch.id %}"><img class="w-100" src="assets/img/course/course-1-1.png" alt="Course Img"></a>
            {% endif %}
        </div>
        <div class="course-content">
            <div class="course-category"><a href="{% url 'main:watches_details' watch.id %}">{{ watch.condition.title }}</a></div>
            {% if watch.special %}
                <div class="course-category"><a href="{% url 'main:watches_details' watch.id %}">{{ watch.special }}</a></div>
            {% endif %}
            <h3 class="course-name"><a href="{% url 'main:watches_details' watch.id %}">{{ watch.brand.title }} {{ watch.title }}</a></h3>
            <div class="course-meta">
                <a><span class="total-student">{{ watch.availability.title }}</span></a>
                <a></i><span class="total-student">Референс: {{ watch.reference }}</span></a>
            </div>
            <div class="course-price">
                <div class="col-auto">
                    <span class="price">₽ {{ watch.price }}<br><br></span>
                    <span class="price">$ {{ watch.get_converted_price }}</span>
                </div>
            </div>
            <div class="course-bottom">
                <button type="button" class="vs-btn style2" data-bs-toggle="modal" data-bs-target="#exampleModal2" data-watch-name="id: {{ watch.id }}, реф.: {{ watch.reference }}"><i class="fas fa-check"></i>Оставить запрос</button>
            </div>
        </div>
    </div>
</div>

watches/templates/includes/watches_list_card.html
<div class="col-sm-6 col-xl-4">
    <div class="course-style1 has-border">
        <div class="image-container">
            {% if watch.image %}
                <a href="{% url 'main:watches_details' watch.id %}" style="display: flex; justify-content: center; align-items: center;"><img src="{{ watch.image.url }}" class="w-75 p-3" alt="Course Img"></a>
            {% else %}
                <a href="{% url 'main:watches_details' watch.id %}" style="display: flex; justify-content: center; align-items: center;"><img src="assets/img/course/course-1-1.png" class="w-100" alt="Course Img"></a>
            {% endif %}
                <div class="course-category">
                    {{ watch.condition.title }}
                    {% if watch.special %}
                        <br>{{ watch.special }}
                    {% endif %}
                </div>
            <button type="button" class="vs-btn style2" data-bs-toggle="modal" data-bs-target="#exampleModal2" data-watch-name="id: {{ watch.id }}, реф.: {{ watch.reference }}"><i class="fas fa-check"></i>Запросить</button>
        </div>
        <div class="course-content">
            <div class="course-top">
                <div class="course-review col-md-5">{{ watch.availability }}</div>
                <div class="col-md-7">
                    <span class="course-price">₽ {{ watch.price }}</span>
                    <span class="course-price">$ {{ watch.get_converted_price }}</span>
                </div>
            </div>
            <h3 class="h5 course-name"><a href="{% url 'main:watches_details' watch.id %}" class="text-inherit">{{ watch.brand.title }}</a></h3>
            <div class="course-teacher"><a class="text-inherit" href="{% url 'main:watches_details' watch.id %}">{{ watch.title }}</a></div>
            <div class="course-review"><a>Референс: {{ watch.reference }}</a></div>
        </div>
    </div>
</div>