watches/forms/urls.py
from django.urls import path

from .views import (call_form_view, footer_form_view, index_page_short_form,
                    watch_request_form_view)

app_name = 'forms'

urlpatterns = [
    path('footer-form', footer_form_view, name='footer_form'),
    path('short-index-form', index_page_short_form, name='short_index'),
    path('call-form', call_form_view, name='call_form'),
    path('watch-request-form', watch_request_form_view, name='watch_request')
]

watches/main/urls.py
from django.urls import path

from .views import (buyback_view_page, index_page_view, search_view,
                    watches_details_page_view, watches_page_view,
                    watches_valuation_page_view)

app_name = 'main'

urlpatterns = [
    path('', index_page_view, name='index'),
    path('search', search_view, name='search'),
    path('buyback', buyback_view_page, name='buyback'),
    path('watches', watches_page_view, name='watches'),
    path(
        'watches-details/<int:watch_id>/',
        watches_details_page_view,
        name='watches_details'
    ),
    path('watches-valuation', watches_valuation_page_view, name='valuation'),
]

watches/utility_pages/urls.py
from django.urls import path

from .views import (about_page_view, confidential_page_view,
                    contacts_page_view, faq_page_view, terms_page_view)

app_name = 'utility_pages'

urlpatterns = [
    path('about', about_page_view, name='about'),
    path('contacts', contacts_page_view, name='contacts'),
    path('faq', faq_page_view, name='faq'),
    path('confidential', confidential_page_view, name='confidential'),
    path('terms', terms_page_view, name='terms'),
]

watches/watches/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'utility_pages.views.page_not_found'
handler500 = 'utility_pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('forms.urls')),
    path('', include('utility_pages.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

watches/forms/models.py
from django.core.validators import MinValueValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from watches.constants import (COMMUNICATION_METHOD_CHOICES,
                               CONDITIONS_FORM_CHOICES, DT_FORMAT,
                               EQUIPMENT_FORM_CHOICES, MIN_PRICE_BUYBACK,
                               MIN_YEAR_BUYBACK, TAGS_CHOICES)

from .validations import max_year_validator


class Base(models.Model):
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата обращения'
    )
    processed = models.BooleanField(
        default=False,
        verbose_name='Обработан?'
    )
    name = models.CharField(
        max_length=56,
        verbose_name='Имя клиента'
    )
    phone = PhoneNumberField(
        verbose_name='Номер телефона'
    )
    text = models.TextField(
        blank=True,
        null=True,
        verbose_name='Текст сообщения',
    )

    class Meta:
        abstract = True
        ordering = ['-pub_date']


class ShortMain(Base):

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Малая форма'
        verbose_name_plural = 'Малая форма'

    def __str__(self):
        return (
            f'Клиент {self.name} оставил обращение от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )


class Call(Base):

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Заказ звонка'
        verbose_name_plural = 'Заказы звонков'

    def __str__(self):
        return (
            f'Клиент {self.name} заказал звонок от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )


class Feedback(Base):
    tags = models.CharField(
        max_length=255,
        choices=TAGS_CHOICES,
        verbose_name='Категория обращения'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'

    def __str__(self):
        return (
            f'Клиент {self.name} оставил обратную связь от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )


class BuybackWatches(Base):
    email = models.EmailField(
        max_length=255,
        verbose_name='Почта'
    )
    communication_method = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=COMMUNICATION_METHOD_CHOICES,
        verbose_name='Предпочитаемый способ связи'
    )
    brand = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Бренд'
    )
    model = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Модель'
    )
    year = models.SmallIntegerField(
        blank=True,
        null=True,
        validators=[
            MinValueValidator(
                MIN_YEAR_BUYBACK,
                message=(
                    f'Значение года не может быть меньше {MIN_YEAR_BUYBACK}г.'
                )
            ),
            max_year_validator
        ],
        verbose_name='Год покупки'
    )
    price = models.IntegerField(
        blank=True,
        null=True,
        validators=[
            MinValueValidator(
                MIN_PRICE_BUYBACK,
                message=f'Значение не может быть меньше {MIN_PRICE_BUYBACK}.'
            )
        ],
        verbose_name='Желаемая сумма (руб.)'
    )
    condition = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=CONDITIONS_FORM_CHOICES,
        verbose_name='Состояние часов'
    )
    equipment = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=EQUIPMENT_FORM_CHOICES,
        verbose_name='Комплектация'
    )

    class Meta:
        verbose_name = 'Выкуп часов'
        verbose_name_plural = 'Выкуп часов'

    def __str__(self):
        return (
            f'Клиент {self.name} оставил запрос на выкуп от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )


class BuybackImage(models.Model):
    buyback = models.ForeignKey(
        'BuybackWatches',
        related_name='images',
        on_delete=models.SET_NULL,
        null=True
    )
    image = models.ImageField(
        upload_to='buyback_images',
        verbose_name='Изображения часов из заявки на выкуп'
    )

    class Meta:
        verbose_name = 'Изображение из заявки'
        verbose_name_plural = 'Изображения из заявки'

    def __str__(self):
        return f'Изображение часов #{self.id}'


class ValuationWatches(Base):
    email = models.EmailField(
        max_length=255,
        verbose_name='Почта'
    )
    communication_method = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=COMMUNICATION_METHOD_CHOICES,
        verbose_name='Предпочитаемый способ связи'
    )
    brand = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Бренд'
    )
    model = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Модель'
    )
    year = models.SmallIntegerField(
        blank=True,
        null=True,
        validators=[
            MinValueValidator(
                MIN_YEAR_BUYBACK,
                message=(
                    f'Значение года не может быть меньше {MIN_YEAR_BUYBACK}г.'
                )
            ),
            max_year_validator
        ],
        verbose_name='Год покупки'
    )
    price = models.IntegerField(
        blank=True,
        null=True,
        validators=[
            MinValueValidator(
                MIN_PRICE_BUYBACK,
                message=f'Значение не может быть меньше {MIN_PRICE_BUYBACK}.'
            )
        ],
        verbose_name='Желаемая сумма (руб.)'
    )
    condition = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=CONDITIONS_FORM_CHOICES,
        verbose_name='Состояние часов'
    )
    equipment = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        choices=EQUIPMENT_FORM_CHOICES,
        verbose_name='Комплектация'
    )

    class Meta:
        verbose_name = 'Оценка часов'
        verbose_name_plural = 'Оценка часов'

    def __str__(self):
        return (
            f'Клиент {self.name} оставил запрос на оценку от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )


class ValuationImage(models.Model):
    valuation = models.ForeignKey(
        'ValuationWatches',
        related_name='val_images',
        on_delete=models.SET_NULL,
        null=True
    )
    image = models.ImageField(
        upload_to='valuation_images',
        verbose_name='Изображения часов из заявки на оценку'
    )

    class Meta:
        verbose_name = 'Изображение из заявки на оценку'
        verbose_name_plural = 'Изображения из заявок на оценку'

    def __str__(self):
        return f'Изображение часов #{self.id}'


class WatchRequest(Base):
    hiden_info = models.TextField(
        verbose_name='Данные запрашиваемых часов',
        help_text=(
            'id: уникальный идентификатор часов; '
            'ref: уникальный референсный номер.'
        )
    )

    class Meta:
        verbose_name = 'Запрос на часы'
        verbose_name_plural = 'Запросы на часы'

    def __str__(self):
        return (
            f'Клиент {self.name} оставил запрос на часы от '
            f'{self.pub_date.strftime(DT_FORMAT)}'
        )

watches/forms/admin.py
from django.contrib import admin

from .models import (BuybackImage, BuybackWatches, Call, Feedback, ShortMain,
                     ValuationImage, ValuationWatches, WatchRequest)


class BuybackImagesInline(admin.TabularInline):
    model = BuybackImage
    extra = 0


class ValuationImagesInline(admin.TabularInline):
    model = ValuationImage
    extra = 0


@admin.register(ValuationWatches)
class ValuationWatchesAdmin(admin.ModelAdmin):
    inlines = [ValuationImagesInline]
    list_display = (
        'processed', 'name', 'phone', 'email', 'communication_method',
        'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'email', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'email', 'pub_date'
    )
    list_filter = (
        'processed',
    )


@admin.register(BuybackWatches)
class BuybackWatchAdmin(admin.ModelAdmin):
    inlines = [BuybackImagesInline]
    list_display = (
        'processed', 'name', 'phone', 'email', 'communication_method',
        'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'email', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'email', 'pub_date'
    )
    list_filter = (
        'processed',
    )


@admin.register(ShortMain)
class ShortMainAdmin(admin.ModelAdmin):
    list_display = (
        'processed', 'name', 'phone', 'text', 'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'text', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'pub_date'
    )
    list_filter = (
        'processed',
    )
    readonly_fields = (
        'name', 'phone', 'text', 'pub_date'
    )


@admin.register(WatchRequest)
class WatchRequestAdmin(admin.ModelAdmin):
    list_display = (
        'processed', 'name', 'phone', 'hiden_info', 'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'hiden_info', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'hiden_info', 'pub_date'
    )
    list_filter = (
        'processed',
    )
    readonly_fields = (
        'name', 'phone', 'hiden_info', 'pub_date'
    )


@admin.register(Call)
class CallAdmin(admin.ModelAdmin):
    list_display = (
        'processed', 'name', 'phone', 'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'pub_date'
    )
    list_filter = (
        'processed',
    )
    exclude = ('text',)
    readonly_fields = ('name', 'phone')


@admin.register(Feedback)
class WatchRequestAdmin(admin.ModelAdmin):
    list_display = (
        'processed', 'name', 'phone', 'pub_date'
    )
    list_display_links = (
        'name', 'phone', 'pub_date'
    )
    list_editable = (
        'processed',
    )
    search_fields = (
        'name', 'phone', 'pub_date'
    )
    list_filter = (
        'processed',
    )
    readonly_fields = (
        'name', 'phone', 'pub_date'
    )

watches/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'
    verbose_name = 'Заявки'

watches/forms/forms.py
from django import forms
from django.core.exceptions import ValidationError

from watches.constants import MAX_IMAGES_FORM

from .models import (BuybackWatches, Call, Feedback, ShortMain,
                     ValuationWatches, WatchRequest)


class ExtendValuationForm(forms.ModelForm):
    valuation_images = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(
            attrs={
                'name': 'valuation_images',
                'id': 'valuation_images',
                'multiple': True,
                'class': 'custom-file-input'
            }
        )
    )

    class Meta:
        model = ValuationWatches
        exclude = ('pub_date', 'processed')

    def clean(self):
        cleaned_data = super().clean()
        images = self.files.getlist('valuation_images')
        if len(images) > MAX_IMAGES_FORM:
            raise ValidationError(
                f'Можно загрузить максимум {MAX_IMAGES_FORM}.'
            )
        elif len(images) < 1:
            raise ValidationError(
                'Необходимо загрузите хотя бы одно изображение'
            )
        return cleaned_data


class ExtendBuybackForm(forms.ModelForm):
    buyback_images = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(
            attrs={
                'name': 'buyback_images',
                'id': 'buyback_images',
                'multiple': True,
                'class': 'custom-file-input'
            }
        )
    )

    class Meta:
        model = BuybackWatches
        exclude = ('pub_date', 'processed')

    def clean(self):
        cleaned_data = super().clean()
        images = self.files.getlist('buyback_images')
        if len(images) > MAX_IMAGES_FORM:
            raise ValidationError(
                f'Можно загрузить максимум {MAX_IMAGES_FORM}.'
            )
        elif len(images) < 1:
            raise ValidationError(
                'Необходимо загрузите хотя бы одно изображение'
            )
        return cleaned_data


class ShortForm(forms.ModelForm):

    class Meta:
        model = ShortMain
        exclude = ('pub_date', 'processed')


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        exclude = ('pub_date', 'processed')


class CallForm(forms.ModelForm):

    class Meta:
        model = Call
        exclude = ('pub_date', 'processed')


class WatchRequestForm(forms.ModelForm):

    class Meta:
        model = WatchRequest
        exclude = ('pub_date', 'processed')

watches/forms/validations.py
from django.core.exceptions import ValidationError
from django.utils.timezone import now


def max_year_validator(value):
    current_year = now().year
    if value > current_year + 1:
        raise ValidationError(
            f'Значение года не может быть больше текущего: {current_year}'
        )

watches/templates/forms/extend_buyback_form_with_close_button.html
<form method="post" action="{% url 'main:buyback' %}" class="form-style5 modal-content" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Закрыть" style="position: absolute; top: 15px; right: 15px; background-color: transparent; border: none; font-size: 30px;">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
    <div class="form-inner">
        <h3 class="form-title h3"><strong class="text-theme">Оставить заявку</strong></h3>
        <h3 class="form-text">Ваши контактные данные</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_name"></label>
                    <input type="text" name="name" placeholder="Имя*" maxlength="56" required id="id_name" value="{{ request.POST.name }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_phone"></label>
                    <input type="tel" name="phone" placeholder="Номер для связи*" required id="id_phone" value="{{ request.POST.phone }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_communication_method"></label>
                    <select name="communication_method" id="id_communication_method">
                        <option selected hidden disabled>Предпочитаемый способ связи</option>
                        <option value="Звонок" {% if request.POST.communication_method == 'Звонок' %} selected {% endif %}>Звонок</option>
                        <option value="На почту" {% if request.POST.communication_method == 'На почту' %} selected {% endif %}>На почту</option>
                        <option value="Telegram" {% if request.POST.communication_method == 'Telegram' %} selected {% endif %}>Telegram</option>
                        <option value="WhatsUp" {% if request.POST.communication_method == 'WhatsUp' %} selected {% endif %}>WhatsUp</option>
                        <option value="Viber" {% if request.POST.communication_method == 'Viber' %} selected {% endif %}>Viber</option>
                      </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_email"></label>
                    <input type="email" name="email" placeholder="Почта*" maxlength="255" required id="id_email" value="{{ request.POST.email }}">
                </div>
            </div>
        </div>
        <h3 class="form-text">Информация о часах</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_brand"></label>
                    <input type="text" name="brand" placeholder="Бренд" maxlength="255" id="id_brand" value="{{ request.POST.brand }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_model"></label>
                    <input type="text" name="model" placeholder="Модель" maxlength="255" id="id_model" value="{{ request.POST.model }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_year"></label>
                    <input type="text" name="year" placeholder="Год покупки" maxlength="255" id="id_year" value="{{ request.POST.year }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_price"></label>
                    <input type="text" name="price" placeholder="Желаемая сумма (руб.)" maxlength="255" id="id_price" value="{{ request.POST.price }}">
                </div>
            </div>
        </div>
        <h3 class="form-text">Состояние и комплектация</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_condition"></label>
                    <select name="condition" id="id_condition">
                        <option selected hidden disabled>Состояние</option>
                        <option value="Идеальное" {% if request.POST.condition == 'Идеальное' %} selected {% endif %}>Идеальное</option>
                        <option value="Новое" {% if request.POST.condition == 'Новое' %} selected {% endif %}>Новое</option>
                        <option value="Естественные следы носки" {% if request.POST.condition == 'Естественные следы носки' %} selected {% endif %}>Естественные следы носки</option>
                        <option value="Есть дефекты" {% if request.POST.condition == 'Есть дефекты' %} selected {% endif %}>Есть дефекты</option>
                        <option value="Требуется ремонт" {% if request.POST.condition == 'Требуется ремонт' %} selected {% endif %}>Требуется ремонт</option>
                      </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_equipment"></label>
                    <select name="equipment" id="id_equipment">
                        <option selected hidden disabled>Комплектация</option>
                        <option value="С упаковкой" {% if request.POST.equipment == 'С упаковкой' %} selected {% endif %}>С упаковкой</option>
                        <option value="Без упаковки" {% if request.POST.equipment == 'Без упаковки' %} selected {% endif %}>Без упаковки</option>
                      </select>
                </div>
            </div>
        </div>
        <style>
            .custom-file-input {
                padding: 15px;
            }
            .custom-file-input::-webkit-file-upload-button {
                display: none;
            }
        </style>
        <h3 class="form-text">Изображения часов и их документов</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input class="custom-file-input" type="file" name="buyback_images" multiple accept="image/*" id="id_buyback_images" />
                    <div class="col text-center">
                        <p> </p>
                        <p class="form-text text-center">Загрузите хотя бы одно, но не более трёх<br>Возможные форматы: png, jpg, jpeg, heic, heiv</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <textarea style="border-radius: 20px;" type="text" name="text" id="id_text" placeholder="Сообщение" value="{{ request.POST.text }}"></textarea>
                </div>
            </div>
        </div>
        <div class="col-12 text-center">
            <button class="vs-btn">Отправить</button>
        </div>
        <div class="col-12 text-center">
            <div class="custom-checkbox notice">
                <label for="wp-comment-cookies-consent"> Нажимая кнопку «Отправить», Вы соглашаетесь с <a href="{% url 'utility_pages:confidential' %}">политикой конфиденциальности</a> и <a href="{% url 'utility_pages:terms' %}">пользовательским соглашением</a>.</label>
            </div>
            <a class="form-link" href="{% url 'utility_pages:faq' %}">Часто задаваемые вопросы</a>
        </div>
    </div>
    <div class="vs-circle color2"></div>
</form>

watches/templates/forms/extend_valuation_form_with_close_button.html
<form method="post" action="{% url 'main:valuation' %}" class="form-style5 modal-content" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Закрыть" style="position: absolute; top: 15px; right: 15px; background-color: transparent; border: none; font-size: 30px;">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
    <div class="form-inner">
        <h3 class="form-title h3"><strong class="text-theme">Оставить заявку</strong></h3>
        <h3 class="form-text">Ваши контактные данные</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_name"></label>
                    <input type="text" name="name" placeholder="Имя*" maxlength="56" required id="id_name" value="{{ request.POST.name }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_phone"></label>
                    <input type="tel" name="phone" placeholder="Номер для связи*" required id="id_phone" value="{{ request.POST.phone }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_communication_method"></label>
                    <select name="communication_method" id="id_communication_method">
                        <option selected hidden disabled>Предпочитаемый способ связи</option>
                        <option value="Звонок" {% if request.POST.communication_method == 'Звонок' %} selected {% endif %}>Звонок</option>
                        <option value="На почту" {% if request.POST.communication_method == 'На почту' %} selected {% endif %}>На почту</option>
                        <option value="Telegram" {% if request.POST.communication_method == 'Telegram' %} selected {% endif %}>Telegram</option>
                        <option value="WhatsUp" {% if request.POST.communication_method == 'WhatsUp' %} selected {% endif %}>WhatsUp</option>
                        <option value="Viber" {% if request.POST.communication_method == 'Viber' %} selected {% endif %}>Viber</option>
                      </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_email"></label>
                    <input type="email" name="email" placeholder="Почта*" maxlength="255" required id="id_email" value="{{ request.POST.email }}">
                </div>
            </div>
        </div>
        <h3 class="form-text">Информация о часах</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_brand"></label>
                    <input type="text" name="brand" placeholder="Бренд" maxlength="255" required id="id_brand" value="{{ request.POST.brand }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_model"></label>
                    <input type="text" name="model" placeholder="Модель" maxlength="255" required id="id_model" value="{{ request.POST.model }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_year"></label>
                    <input type="text" name="year" placeholder="Год покупки" maxlength="255" id="id_year" value="{{ request.POST.year }}">
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_price"></label>
                    <input type="text" name="price" placeholder="Желаемая сумма (руб.)" maxlength="255" id="id_price" value="{{ request.POST.price }}">
                </div>
            </div>
        </div>
        <h3 class="form-text">Состояние и комплектация</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_condition"></label>
                    <select name="condition" id="id_condition">
                        <option selected hidden disabled>Состояние</option>
                        <option value="Идеальное" {% if request.POST.condition == 'Идеальное' %} selected {% endif %}>Идеальное</option>
                        <option value="Новое" {% if request.POST.condition == 'Новое' %} selected {% endif %}>Новое</option>
                        <option value="Естественные следы носки" {% if request.POST.condition == 'Естественные следы носки' %} selected {% endif %}>Естественные следы носки</option>
                        <option value="Есть дефекты" {% if request.POST.condition == 'Есть дефекты' %} selected {% endif %}>Есть дефекты</option>
                        <option value="Требуется ремонт" {% if request.POST.condition == 'Требуется ремонт' %} selected {% endif %}>Требуется ремонт</option>
                      </select>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <label for="id_equipment"></label>
                    <select name="equipment" id="id_equipment">
                        <option selected hidden disabled>Комплектация</option>
                        <option value="С упаковкой" {% if request.POST.equipment == 'С упаковкой' %} selected {% endif %}>С упаковкой</option>
                        <option value="Без упаковки" {% if request.POST.equipment == 'Без упаковки' %} selected {% endif %}>Без упаковки</option>
                      </select>
                </div>
            </div>
        </div>
        <style>
            .custom-file-input {
                padding: 15px;
            }
            .custom-file-input::-webkit-file-upload-button {
                display: none;
            }
        </style>
        <h3 class="form-text">Изображения часов и их документов</h3>
        <div class="row">
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <input class="custom-file-input" type="file" name="valuation_images" multiple accept="image/*" id="id_valuation_images" />
                    <div class="col text-center">
                        <p> </p>
                        <p class="form-text">Загрузите хотя бы одно, но не более трёх<br>Возможные форматы: png, jpg, jpeg, heic, heiv</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="form-group">
                    <textarea style="border-radius: 20px;" type="text" name="text" id="id_text" placeholder="Сообщение" value="{{ request.POST.text }}"></textarea>
                </div>
            </div>
        </div>
        <div class="col-12 text-center">
            <button class="vs-btn">Отправить</button>
        </div>
        <div class="col-12 text-center">
            <div class="custom-checkbox notice">
                <label for="wp-comment-cookies-consent"> Нажимая кнопку «Отправить», Вы соглашаетесь с <a href="{% url 'utility_pages:confidential' %}">политикой конфиденциальности</a> и <a href="{% url 'utility_pages:terms' %}">пользовательским соглашением</a>.</label>
            </div>
            <a class="form-link" href="{% url 'utility_pages:faq' %}">Часто задаваемые вопросы</a>
        </div>
    </div>
    <div class="vs-circle color2"></div>
</form>